"""empty message

Revision ID: 32f058aab626
Revises: 98d3f7af0722
Create Date: 2020-09-05 01:43:11.789710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f058aab626'
down_revision = '98d3f7af0722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event', 'names', ['Theme'], ['Name'])
    op.add_column('names', sa.Column('Event_ID', sa.String(), nullable=False))
    op.drop_column('names', 'Event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('names', sa.Column('Event', sa.VARCHAR(), nullable=False))
    op.drop_column('names', 'Event_ID')
    op.drop_constraint(None, 'event', type_='foreignkey')
    # ### end Alembic commands ###
