"""empty message

Revision ID: 98d3f7af0722
Revises: 
Create Date: 2020-09-05 00:22:10.795166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d3f7af0722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
                    sa.Column('Name', sa.String(length=25), nullable=False),
                    sa.Column('Theme', sa.String(length=25), nullable=False),
                    sa.PrimaryKeyConstraint('Name')
                    )
    op.create_table('names',
                    sa.Column('Name', sa.String(length=50), nullable=False),
                    sa.Column('Event', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('Name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names')
    op.drop_table('event')
    # ### end Alembic commands ###
